name: YT-AT
on: 
  workflow_dispatch:
    inputs:
      VERSION:
        description: '17-32-35 > 17.32.35 is the YouTube version that revanced supports tool, you can import higher version but maybe broken some features.'
        required: true
        default: '17-33-42'
      DEVICE:
        description: 'Select device'
        required: true
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      FEATURE:
        description: 'Turn off the feature, Add spaces to distinguish each feature'
        required: true
        default: 'always-autorepeat hide-autoplay-button '
      TYPE:
        description: 'Sign in microg (No Root)'
        required: false
        type: boolean
        default: true
      AMOLED:
        description: 'Dark Theme'
        required: false
        type: boolean
        default: true
      ICONS:
        description: 'Original icon & Name'
        required: false
        type: boolean
        default: true
      OPTIMIZATION:
        description: 'Video loaded speed'
        required: false
        type: boolean
        default: true
      CREATE:
        description: 'Show create video button'
        required: false
        type: boolean
        default: true
      SHORTS:
        description: 'Show button shorts video'
        required: false
        type: boolean
        default: true
      ROUND:
        description: 'Pip rounded (root)'
        required: false
        type: boolean
        default: true
jobs:
  build:
    name: 'Open build...'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: ${{ inputs.AMOLED }}
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: ${{ inputs.TYPE }}
          SHORTS: ${{ inputs.SHORTS }}
          CREATE: ${{ inputs.CREATE }}

        run: |
          chmod -R 777 Tools/*
          SVision="17.33.42"
          chmod 777 .github/install.sh
          . .github/install.sh
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: YT-AT ${{ github.event.inputs.VERSION }}
          tag_name: V${{ github.event.inputs.VERSION }}
          files: Up/*
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
